### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by aykutkardas** [toltarisa/MultiSelectDropdownComponent#5]
Bir kaç kısmı inceleyip. Önerilerde bulundum. Fırsat bulursam tekrar bakacağım. Eline sağlık. 

**1.** https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L35
```js
    const filteredItems = items.filter(item => {
      return item !== fruit;
    });
```
Halihazırda arrow function yazdığın için yukarıdaki yerine şöyle yapabilirsin.
```js
    const filteredItems = items.filter(item => item !== fruit);
```

**2**
https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L47
```js
        <div
          style={{ display: items.length === 0 ? 'none' : 'flex' }}
          onClick={this.setSelectVisible}
          className="pill-wrapper"
        >
          {items.map((item, index) => (
            <Pill
              remove={this.removeItemFromWrapper}
              key={index}
              fruit={item}
            />
          ))}
        </div>
```

Burada da style in alacağı bir değer içinde koşul yazmaktansa şu şekilde yazmak daha temiz olabilir.

```js
        {items.length > 0 && (
          <div
            style={{ display: "flex" }}
            onClick={this.setSelectVisible}
            className="pill-wrapper"
          >
            {items.map((item, index) => (
              <Pill
                remove={this.removeItemFromWrapper}
                key={index}
                fruit={item}
              />
            ))}
          </div>
        )}
```
Yine de mümkünse style değerlerini inline vermek yerine zaten tanımlamış olduğun `pill-wrapper` sınıfına css olarak yazmanı tavsiye ederim.

**3.**
https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L16

```js
   onSelect = event => {
      event.preventDefault();
      let items = [...this.state.items];
      items.push(event.target.value);
      this.setState({
        selectedItem: event.target.value,
        items,
        display: "none"
      });
    };
```

Burada gözüme çarpan iki kısım var biri birden fazla kez kullanılan `event.target.value` değerinin destruct edilmemesi diğeri de state teki önceki bir değere ulaşma şekli. 

React statelerin senkron bir şekilde güncelleneceğini taahüt etmez. Bu yüzde state güncellerken önceki değerine ihtiyacın varsa prevState yöntemiyle almalısın. 

`setState` metoduna obje yerine fonksiyon gönderirsen sana callback olarak mevcut state i güncel bir şekilde verir. O yüzden burayı da aşağıda ki gibi yazmak hem daha temiz hem daha sağlıklı olacaktır.

```js
    onSelect = event => {
      event.preventDefault();
      
      const { value } = event.target;

      this.setState(({ items }) => ({
        selectedItem: value,
        items: [...items, value],
        display: "none"
      }));
    };
```  

**4.**
https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L28

Bu metot Türkçe karakterleri doğru bir şekilde çevirmeyecektir.

**Comment by toltarisa** [comment]
> Bir kaç kısmı inceleyip. Önerilerde bulundum. Fırsat bulursam tekrar bakacağım. Eline sağlık.
> 
> **1.**
> 
> https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L35
> 
> ```js
>     const filteredItems = items.filter(item => {
>       return item !== fruit;
>     });
> ```
> 
> Halihazırda arrow function yazdığın için yukarıdaki yerine şöyle yapabilirsin.
> 
> ```js
>     const filteredItems = items.filter(item => item !== fruit);
> ```
> 
> **2**
> https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L47
> 
> ```js
>         <div
>           style={{ display: items.length === 0 ? 'none' : 'flex' }}
>           onClick={this.setSelectVisible}
>           className="pill-wrapper"
>         >
>           {items.map((item, index) => (
>             <Pill
>               remove={this.removeItemFromWrapper}
>               key={index}
>               fruit={item}
>             />
>           ))}
>         </div>
> ```
> 
> Burada da style in alacağı bir değer içinde koşul yazmaktansa şu şekilde yazmak daha temiz olabilir.
> 
> ```js
>         {items.length > 0 && (
>           <div
>             style={{ display: "flex" }}
>             onClick={this.setSelectVisible}
>             className="pill-wrapper"
>           >
>             {items.map((item, index) => (
>               <Pill
>                 remove={this.removeItemFromWrapper}
>                 key={index}
>                 fruit={item}
>               />
>             ))}
>           </div>
>         )}
> ```
> 
> Yine de mümkünse style değerlerini inline vermek yerine zaten tanımlamış olduğun `pill-wrapper` sınıfına css olarak yazmanı tavsiye ederim.
> 
> **3.**
> https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L16
> 
> ```js
>    onSelect = event => {
>       event.preventDefault();
>       let items = [...this.state.items];
>       items.push(event.target.value);
>       this.setState({
>         selectedItem: event.target.value,
>         items,
>         display: "none"
>       });
>     };
> ```
> 
> Burada gözüme çarpan iki kısım var biri birden fazla kez kullanılan `event.target.value` değerinin destruct edilmemesi diğeri de state teki önceki bir değere ulaşma şekli.
> 
> React statelerin senkron bir şekilde güncelleneceğini taahüt etmez. Bu yüzde state güncellerken önceki değerine ihtiyacın varsa prevState yöntemiyle almalısın.
> 
> `setState` metoduna obje yerine fonksiyon gönderirsen sana callback olarak mevcut state i güncel bir şekilde verir. O yüzden burayı da aşağıda ki gibi yazmak hem daha temiz hem daha sağlıklı olacaktır.
> 
> ```js
>     onSelect = event => {
>       event.preventDefault();
>       
>       const { value } = event.target;
> 
>       this.setState(({ items }) => ({
>         selectedItem: value,
>         items: [...items, value],
>         display: "none"
>       }));
>     };
> ```
> 
> **4.**
> https://github.com/toltarisa/MultiSelectDropdownComponent/blob/7f799ae1a1d5335c2b61d3b104c115e4353c47a5/src/App.js#L28
> 
> Bu metot Türkçe karakterleri doğru bir şekilde çevirmeyecektir.

Eline sağlık gözden geçireceğim

**Comment by toltarisa** [comment]
Eline sağlık @aykutkardas .Kesinlikle gözden geçireceğim .
